version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  nodeapi:
    container_name: studentapi
    build: .
    ports: 
      - "5001:4000" 
    environment:
      PORT: 4000
      MONGODB_URL: mongodb://mongo_db:27017
      DB_NAME: Testdb1
    depends_on:
      - mongo_db
  reactclient:
    image: difname
    container_name: reactclient1000
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    environment:
      PORT: 3000
      API_URL: locahost://studentapi:3047
    ports:
      - "3047:3000"
    depends_on:
      - studentapi
volumes:
  mongo_db: {}
